---
- hosts: mywebservers
  become: yes
  tasks:
  - name: in this task , i want to install apache2 webserver on ubuntu
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"
  - name: in this task, i want to start webserver on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"
  - name: in this task, i want to install httpd webserver on redhat
    dnf:
      name: "{{mywebpackeonredhat}}"
      state: present
    when: ansible_os_family== "RedHat"
  - name: in this task, i want to start webserver on redhat
    service:
      name: "{{mywebpackeonredhat}}"
      state: started
    when: ansible_os_family== "RedHat"
    

